### ISSUE TITLE
feed-loader: InvalidContentEntryFrontmatterError with Pixelfed

### ISSUE THREAD

**Issue by FjellOverflow** [ascorbic/astro-loaders#43]
I'm trying to parse any Pixelfed feed (e.g. `https://pixelfed.social/users/dansup.atom`).

On `astro sync` / `astro dev` I get
```
AstroError [InvalidContentEntryFrontmatterError]: **pixelfeed → https://pixelfed.social/p/dansup/747009548654602534** frontmatter does not match collection schema.
**enclosures.0.length**: Expected type `"string"`, received "null"
```

I figure the feeds schema is problematic, but the error is not hinting at where exactly the problem occurs or how I can mitigate it.

**Comment by ascorbic** [comment]
Thanks for the report. I've got a fix in.
